export enum ActionType {
  UPDATE_COLLECTION = 'UPDATE_COLLECTION',
  REMOVE_COLLECTION = 'REMOVE_COLLECTION',
  UPDATE_OFFSET = 'UPDATE_OFFSET',
  REMOVE_OFFSET = 'REMOVE_OFFSET',
  SOLVED = 'SOLVED',
  NEW_GAME = 'NEW_GAME',
}
