export enum ActionType {
  TOGGLE_ERROR = 'TOGGLE_ERROR',
  OPEN_TRAINING = 'OPEN_TRAINING',
  CLOSE_TRAINING = 'CLOSE_TRAINING',
  SHOW_TRAIN_LOADER = 'SHOW_TRAIN_LOADER',
  HIDE_TRAIN_LOADER = 'HIDE_TRAIN_LOADER',
}
