export const eng = {
  title: 'AUDIOCALL',
  description: 'Choose the correct translation of the heard word from 5 options',
  myWordsMode: 'In the "My words" mode, words from your dictionary will sound',
  freeGameMode: 'In the "Free Game" mode will be frequently used words of the selected difficulty',
  buttons: {
    myWords: 'My words',
    freeGame: 'Free game',
    notKnow: 'DO NOT KNOW',
    leave: 'Yes, leave',
    stay: 'No, i continue',
    playAgain: 'PLAY AGAIN',
    statistic: 'STATISTIC',
    toMain: 'TO MAIN',
  },
  level: 'Level',
  round: 'Round',
  modalMessage: {
    titleNotOver: 'Are you sure? The training is not over!',
    contentNotOver: 'If you exit the game, your progress will not be saved.',
    titleNotEnough: 'There are not enough words in the dictionary.',
    contentNotEnough: 'It seems that the dictionary does not have enough words for the game. But you can play in free play mode. Want to quit the game?',
    titleError: 'Oh! Error!',
    contentError: 'Something went wrong. Please try again later. Quit the game?',
  },
  shortStatistic: {
    titleNotBad: 'Not bad, but more effort',
    titleKeepItUp: 'Sumptuously! Keep it up!',
    titleGood: 'Good, but there is work to do.',
    titleFailure: 'Failure, keep training',
    titleNeedRepeat: 'You need to repeat the words more often',
    errors: 'ERRORS:',
    know: 'KNOW:',
    deleteHint: 'Delete from dictionary',
  },
  longStatistic: {
    time: 'Time:',
    level: 'Level:',
    group: 'Group:',
    page: 'Page:',
    success: 'Success:',
    failed: 'Failed:',
    myWords: 'My words',
  },
};

export const ru = {
  title: 'АУДИОВЫЗОВ',
  description: 'Выбери правильный перевод услышанного слова из 5 вариантов.',
  myWordsMode: 'В режиме "Мои слова" будут звучать слова из Вашего словаря',
  freeGameMode: 'В режиме "Свободная игра" будут часто употребляемые слова выбранной сложности',
  buttons: {
    myWords: 'Мои слова',
    freeGame: 'Свободная игра',
    notKnow: 'НЕ ЗНАЮ',
    leave: 'Да, уйти',
    stay: 'Нет, я продолжу',
    playAgain: 'ИГРАТЬ СНОВА',
    statistic: 'СТАТИСТИКА',
    toMain: 'НА ГЛАВНУЮ',
  },
  level: 'Уровень',
  round: 'Раунд',
  modalMessage: {
    titleNotOver: 'Вы уверены? Тренировка не закончена!',
    contentNotOver: 'Если вы выйдете из игры, ваш прогресс не будет сохранен.',
    titleNotEnough: 'Недостаточно слов в словаре.',
    contentNotEnough: 'Кажется, в словаре недостаточно слов для игры. Но Вы можете играть в режиме свободной игры. Хотите выйти из игры?',
    titleError: 'Ой! Ошибка!',
    contentError: 'Что-то пошло не так. Попробуйте, пожалуйста, позже. Выйти из игры?',
  },
  shortStatistic: {
    titleNotBad: 'Неплохо, но нужно больше усилий',
    titleKeepItUp: 'Великолепно! Так держать!',
    titleGood: 'Хорошо, но есть над чем поработать',
    titleFailure: 'Неудача, продолжайте тренироваться',
    titleNeedRepeat: 'Нужно чаще повторять слова',
    errors: 'ОШИБКИ:',
    know: 'ЗНАЮ:',
    deleteHint: 'Удалить из словаря',
  },
  longStatistic: {
    time: 'Время:',
    level: 'Уровень:',
    group: 'Группа:',
    page: 'Страница:',
    success: 'Правильно:',
    failed: 'Ошибки:',
    myWords: 'Мои слова',
  },
};
