export enum ActionType {
  AUDIO_ENABLE = 'AUDIO_ENABLE',
  AUDIO_DISABLE = 'AUDIO_DISABLE',
  TRANSLATE_ENABLE = 'TRANSLATE_ENABLE',
  TRANSLATE_DISABLE = 'TRANSLATE_DISABLE',
  BACKGROUND_ENABLE = 'BACKGROUND_ENABLE',
  BACKGROUND_DISABLE = 'BACKGROUND_DISABLE',
  SPEAKER_ENABLE = 'SPEAKER_ENABLE',
  SPEAKER_DISABLE = 'SPEAKER_DISABLE',
  SET_TO_USER_PREFERENCIES = 'SET_TO_USER_PREFERENCIES',
}
