export enum ActionType {
  FETCH_WORDS = 'FETCH_WORDS',
  TRANSLATE_WORD = 'TRANSLATE_WORD',
  BACKGROUND_WORD = 'BACKGROUND_WORD',
  INIT_WORD_STATISTICS = 'INIT_WORD_STATISTICS',
  WIN = 'WIN',
  MISTAKE = 'MISTAKE',
  RESET_STATISTICS = 'RESET_STATISTICS',
  SUCCES_WORD = 'SUCCES_WORD',
  FAILED_WORD = 'FAILED_WORD',
}
