export enum ActionType {
  ENABLE_DONT_KNOW_BTN = 'ENABLE_DONT_KNOW_BTN',
  DISABLE_DONT_KNOW_BTN = 'DISABLE_DONT_KNOW_BTN',
  ENABLE_CHECK_BTN = 'ENABLE_CHECK_BTN',
  DISABLE_CHECK_BTN = 'DISABLE_CHECK_BTN',
  ENABLE_CONTINUE_BTN = 'ENABLE_CONTINUE_BTN',
  DISABLE_CONTINUE_BTN = 'DISABLE_CONTINUE_BTN',
  ENABLE_RESULTS_BTN = 'ENABLE_RESULTS_BTN',
  DISABLE_RESULTS_BTN = 'DISABLE_RESULTS_BTN',
  ENABLE_STATISTIC_BTN = 'ENABLE_STATISTIC_BTN',
  DISABLE_STATISTIC_BTN = 'DISABLE_STATISTIC_BTN',
}
