export enum ActionType {
  OPEN_MODAL = 'OPEN_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  SET_INFO = 'SET_INFO',
  SET_THEME = 'SET_THEME',
  HANDLE_SETTINGS = 'HANDLE_SETTINGS',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  UPDATE_AMOUNT = 'UPDATE_AMOUNT',
  CHANGE_LANG = 'CHANGE_LANG',
  UPDATE_STUDY_SETTINGS = 'UPDATE_STUDY_SETTINGS',
  OPEN_ERROR_MODAL = 'OPEN_ERROR_MODAL',
  CLOSE_ERROR_MODAL = 'CLOSE_ERROR_MODAL',
}
