export enum ActionType {
  OPEN_STATISTIC = 'OPEN_STATISTIC',
  CLOSE_STATISTIC = 'CLOSE_STATISTIC',
  UPDATE_DATE = 'UPDATE_DATE',
  UPDATE_TIME = 'UPDATE_TIME',
  UPDATE_LEVELS = 'UPDATE_LEVELS',
  UPDATE_FAILED = 'UPDATE_FAILED',
  UPDATE_SUCCESS = 'UPDATE_SUCCESS',
}
